// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretSantaApplication.Data;

namespace SecretSantaApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SecretSantaApplication.Models.Profile", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterToSecretSanta")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailAddress");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.Room", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.SecretSanta", b =>
                {
                    b.Property<string>("Santa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Santa");

                    b.ToTable("SecretSantas");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.User", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.HasKey("EmailAddress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.UserToRoom", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailAddress", "Name");

                    b.HasIndex("Name");

                    b.ToTable("UserToRooms");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.UserToRoom", b =>
                {
                    b.HasOne("SecretSantaApplication.Models.User", "User")
                        .WithMany("UserToRooms")
                        .HasForeignKey("EmailAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecretSantaApplication.Models.Room", "Room")
                        .WithMany("UserToRooms")
                        .HasForeignKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.Room", b =>
                {
                    b.Navigation("UserToRooms");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.User", b =>
                {
                    b.Navigation("UserToRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
