// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretSantaApplication.Data;

namespace SecretSantaApplication.Migrations
{
    [DbContext(typeof(Db_AppContext))]
    partial class Db_AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("SecretSantaApplication.Models.Profile", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterToSecretSanta")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailAddress");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.Room", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.SecretSanta", b =>
                {
                    b.Property<string>("Santa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Santa");

                    b.ToTable("SecretSantas");
                });

            modelBuilder.Entity("SecretSantaApplication.Models.User", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(18);

                    b.HasKey("EmailAddress");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
